what is pandas ?
pandasnis a python library used for data cleaning,analysis,and manupilation.
works like excel but faster.
helps loads the data ,clean,filter,analyze data.
uses: data science.ml.finance,analytics,and automating data tasks.

In [3]:
import pandas as pd
pd.__version__

'2.2.2'

pandas data structures 
series---one dimensional coloumn
dataframe---table with rows + columns

In [4]:
s=pd.Series([10,2,32,23])
s

0    10
1     2
2    32
3    23
dtype: int64

READING CSV FILES

In [5]:
df=pd.DataFrame({
    "name":["jasmin","yasmin"],
    "age":[20,19]
})
print(df)

     name  age
0  jasmin   20
1  yasmin   19

In [6]:
student={
    "name":["jasmin","yasmin","mubina","zoya","zara"],
    "rollno":[1,2,3,4,5],
     "dept":["cse","ece","cse","cse","ece"]
}
pd.DataFrame(student)

     name  rollno dept
0  jasmin       1  cse
1  yasmin       2  ece
2  mubina       3  cse
3    zoya       4  cse
4    zara       5  ece

In [7]:
import pandas as pd
pd.read_csv("weather_data.csv")

         Date          City  Temperature_C  Humidity_% Condition
0  01-01-2025      Hyderbad           28.0        60.0     Sunny
1  02-01-2025    Vijayawada           29.0        62.0     Sunny
2  03-01-2025  Viskhapatnam            NaN        58.0    Cloudy
3  04-01-2025      Kakinada           31.0        55.0    Cloudy
4  05-01-2025      Banglore            NaN        57.0     Rainy
5  06-01-2025        Mumbai           33.0         NaN     Rainy
6  07-01-2025       Chennai           34.0        61.0     Sunny
7  08-01-2025    Rajamundry           32.0        63.0    Cloudy
8  09-01-2025         Eluru            NaN        64.0     Rainy
9  10-01-2025    Anakapalli           29.0        62.0     Sunny

reading excel file

In [8]:
df=pd.read_excel("weather_data_XL.xlsx")
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    Hyderbad             28          60     Sunny
1 2025-01-02    Hyderbad             29          62     Sunny
2 2025-01-03    Hyderbad             30          58    Cloudy
3 2025-01-04    Hyderbad             31          55    Cloudy
4 2025-01-05    Banglore             32          57     Rainy
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

writing the data into files
df.to_csv("data.csv",index=false)
df.to_excel("new.xlsx",sheet_name="weather_data",index=false)

In [9]:
#save file as csv and name is data.csv and save the file wih preventing row numbers from being saved.
df.to_csv("data.csv",index=False)

In [10]:
df.to_excel("new.xlsx",sheet_name="weather_data",index=False)

In [11]:
#first five rows
df.head()

        Date      City  Temperature_C  Humidity_% Condition
0 2025-01-01  Hyderbad             28          60     Sunny
1 2025-01-02  Hyderbad             29          62     Sunny
2 2025-01-03  Hyderbad             30          58    Cloudy
3 2025-01-04  Hyderbad             31          55    Cloudy
4 2025-01-05  Banglore             32          57     Rainy

In [12]:
df.head(10)

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    Hyderbad             28          60     Sunny
1 2025-01-02    Hyderbad             29          62     Sunny
2 2025-01-03    Hyderbad             30          58    Cloudy
3 2025-01-04    Hyderbad             31          55    Cloudy
4 2025-01-05    Banglore             32          57     Rainy
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

In [13]:
df.tail()

        Date        City  Temperature_C  Humidity_% Condition
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

In [14]:
df.tail(3)

        Date        City  Temperature_C  Humidity_% Condition
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           10 non-null     datetime64[ns]
 1   City           10 non-null     object
 2   Temperature_C  10 non-null     int64
 3   Humidity_%     10 non-null     int64
 4   Condition      10 non-null     object
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 532.0+ bytes

In [16]:
df["Date"]

0   2025-01-01
1   2025-01-02
2   2025-01-03
3   2025-01-04
4   2025-01-05
5   2025-01-06
6   2025-01-07
7   2025-01-08
8   2025-01-09
9   2025-01-10
Name: Date, dtype: datetime64[ns]

In [17]:
df.Date

0   2025-01-01
1   2025-01-02
2   2025-01-03
3   2025-01-04
4   2025-01-05
5   2025-01-06
6   2025-01-07
7   2025-01-08
8   2025-01-09
9   2025-01-10
Name: Date, dtype: datetime64[ns]

In [18]:
df.shape

(10, 5)

In [19]:
df[4:8]

        Date      City  Temperature_C  Humidity_% Condition
4 2025-01-05  Banglore             32          57     Rainy
5 2025-01-06  Banglore             33          59     Rainy
6 2025-01-07  Banglore             34          61     Sunny
7 2025-01-08  Banglore             32          63    Cloudy

In [20]:
df.columns

Index(['Date', 'City', 'Temperature_C', 'Humidity_%', 'Condition'], dtype='object')

In [21]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [22]:
df.dtypes

Date             datetime64[ns]
City                     object
Temperature_C             int64
Humidity_%                int64
Condition                object
dtype: object

In [23]:
df[["Date","Condition"]]

        Date Condition
0 2025-01-01     Sunny
1 2025-01-02     Sunny
2 2025-01-03    Cloudy
3 2025-01-04    Cloudy
4 2025-01-05     Rainy
5 2025-01-06     Rainy
6 2025-01-07     Sunny
7 2025-01-08    Cloudy
8 2025-01-09     Rainy
9 2025-01-10     Sunny

MISSING VALUES

In [24]:
df.isnull() #check missing values

    Date   City  Temperature_C  Humidity_%  Condition
0  False  False          False       False      False
1  False  False          False       False      False
2  False  False          False       False      False
3  False  False          False       False      False
4  False  False          False       False      False
5  False  False          False       False      False
6  False  False          False       False      False
7  False  False          False       False      False
8  False  False          False       False      False
9  False  False          False       False      False

In [28]:
import pandas as pd
df=pd.read_csv("weather_data.csv")

In [29]:
df.isnull()

    Date   City  Temperature_C  Humidity_%  Condition
0  False  False          False       False      False
1  False  False          False       False      False
2  False  False           True       False      False
3  False  False          False       False      False
4  False  False           True       False      False
5  False  False          False        True      False
6  False  False          False       False      False
7  False  False          False       False      False
8  False  False           True       False      False
9  False  False          False       False      False

In [33]:
df.isnull().sum()

Date             0
City             0
Temperature_C    3
Humidity_%       1
Condition        0
dtype: int64

In [40]:
df=pd.DataFrame({
    "name":["jasmin","yasmin","mubina"],
    "age":[20,19,None]})
df

     name   age
0  jasmin  20.0
1  yasmin  19.0
2  mubina   NaN

In [41]:
df.isnull()

    name    age
0  False  False
1  False  False
2  False   True

HANDLING MISSING VALUES

In [49]:
df["age"]=df["age"].fillna(df["age"].mean())
df

     name   age
0  jasmin  20.0
1  yasmin  19.0
2  mubina  19.5

In [50]:
df=pd.DataFrame({
    "name":["jasmin","yasmin","mubina"],
    "age":[20,19,None]})
df

     name   age
0  jasmin  20.0
1  yasmin  19.0
2  mubina   NaN

In [51]:
df_clean=df.dropna()
df_clean

     name   age
0  jasmin  20.0
1  yasmin  19.0

DUPLICATES

In [53]:
df=pd.DataFrame({
    "name":["jasmin","yasmin","jasmin"],
    "regs":[201,191,201]})
df

     name  regs
0  jasmin   201
1  yasmin   191
2  jasmin   201

In [54]:
df.duplicated()

0    False
1    False
2     True
dtype: bool

In [55]:
df=df.drop_duplicates()
df

     name  regs
0  jasmin   201
1  yasmin   191

STATISTICS

In [56]:
df=pd.read_excel("weather_data_XL.xlsx")
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    Hyderbad             28          60     Sunny
1 2025-01-02    Hyderbad             29          62     Sunny
2 2025-01-03    Hyderbad             30          58    Cloudy
3 2025-01-04    Hyderbad             31          55    Cloudy
4 2025-01-05    Banglore             32          57     Rainy
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

In [57]:
df["Temperature_C"].std()

1.911950719959998

In [58]:
df["Temperature_C"].var()

3.6555555555555554

In [59]:
df["Temperature_C"].max()

34

In [60]:
df["Temperature_C"].min()

28

In [61]:
df["Temperature_C"].mean()

30.9

In [62]:
df["Temperature_C"].describe()

count    10.000000
mean     30.900000
std       1.911951
min      28.000000
25%      29.250000
50%      31.000000
75%      32.000000
max      34.000000
Name: Temperature_C, dtype: float64

In [65]:
df[df.Temperature_C==df.Temperature_C.max()]

        Date      City  Temperature_C  Humidity_% Condition
6 2025-01-07  Banglore             34          61     Sunny

In [66]:
df.City[df.Temperature_C==df.Temperature_C.max()]

6    Banglore
Name: City, dtype: object

In [67]:
df.count()

Date             10
City             10
Temperature_C    10
Humidity_%       10
Condition        10
dtype: int64

In [68]:
df["City"].nunique()

3

In [70]:
df["City"].value_counts()

City
Hyderbad      4
Banglore      4
Vijayawada    2
Name: count, dtype: int64

STRING CLEANING

In [71]:
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    Hyderbad             28          60     Sunny
1 2025-01-02    Hyderbad             29          62     Sunny
2 2025-01-03    Hyderbad             30          58    Cloudy
3 2025-01-04    Hyderbad             31          55    Cloudy
4 2025-01-05    Banglore             32          57     Rainy
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

In [72]:
df["City"]=df["City"].str.lower()
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    hyderbad             28          60     Sunny
1 2025-01-02    hyderbad             29          62     Sunny
2 2025-01-03    hyderbad             30          58    Cloudy
3 2025-01-04    hyderbad             31          55    Cloudy
4 2025-01-05    banglore             32          57     Rainy
5 2025-01-06    banglore             33          59     Rainy
6 2025-01-07    banglore             34          61     Sunny
7 2025-01-08    banglore             32          63    Cloudy
8 2025-01-09  vijayawada             31          64     Rainy
9 2025-01-10  vijayawada             29          62     Sunny

In [73]:
df["City"]=df["City"].str.upper()
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    HYDERBAD             28          60     Sunny
1 2025-01-02    HYDERBAD             29          62     Sunny
2 2025-01-03    HYDERBAD             30          58    Cloudy
3 2025-01-04    HYDERBAD             31          55    Cloudy
4 2025-01-05    BANGLORE             32          57     Rainy
5 2025-01-06    BANGLORE             33          59     Rainy
6 2025-01-07    BANGLORE             34          61     Sunny
7 2025-01-08    BANGLORE             32          63    Cloudy
8 2025-01-09  VIJAYAWADA             31          64     Rainy
9 2025-01-10  VIJAYAWADA             29          62     Sunny

In [75]:
df["City"]=df["City"].str.replace("HYDERBAD","CHENNAI")
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01     CHENNAI             28          60     Sunny
1 2025-01-02     CHENNAI             29          62     Sunny
2 2025-01-03     CHENNAI             30          58    Cloudy
3 2025-01-04     CHENNAI             31          55    Cloudy
4 2025-01-05    BANGLORE             32          57     Rainy
5 2025-01-06    BANGLORE             33          59     Rainy
6 2025-01-07    BANGLORE             34          61     Sunny
7 2025-01-08    BANGLORE             32          63    Cloudy
8 2025-01-09  VIJAYAWADA             31          64     Rainy
9 2025-01-10  VIJAYAWADA             29          62     Sunny

In [76]:
df.sort_values(by="Temperature_C",ascending=True)

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01     CHENNAI             28          60     Sunny
1 2025-01-02     CHENNAI             29          62     Sunny
9 2025-01-10  VIJAYAWADA             29          62     Sunny
2 2025-01-03     CHENNAI             30          58    Cloudy
3 2025-01-04     CHENNAI             31          55    Cloudy
8 2025-01-09  VIJAYAWADA             31          64     Rainy
4 2025-01-05    BANGLORE             32          57     Rainy
7 2025-01-08    BANGLORE             32          63    Cloudy
5 2025-01-06    BANGLORE             33          59     Rainy
6 2025-01-07    BANGLORE             34          61     Sunny

In [77]:
df.sort_values(by="Temperature_C",ascending=False)

        Date        City  Temperature_C  Humidity_% Condition
6 2025-01-07    BANGLORE             34          61     Sunny
5 2025-01-06    BANGLORE             33          59     Rainy
4 2025-01-05    BANGLORE             32          57     Rainy
7 2025-01-08    BANGLORE             32          63    Cloudy
3 2025-01-04     CHENNAI             31          55    Cloudy
8 2025-01-09  VIJAYAWADA             31          64     Rainy
2 2025-01-03     CHENNAI             30          58    Cloudy
1 2025-01-02     CHENNAI             29          62     Sunny
9 2025-01-10  VIJAYAWADA             29          62     Sunny
0 2025-01-01     CHENNAI             28          60     Sunny

In [79]:
df.sort_values(by=["Temperature_C","Humidity_%"],ascending=[True,True])

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01     CHENNAI             28          60     Sunny
1 2025-01-02     CHENNAI             29          62     Sunny
9 2025-01-10  VIJAYAWADA             29          62     Sunny
2 2025-01-03     CHENNAI             30          58    Cloudy
3 2025-01-04     CHENNAI             31          55    Cloudy
8 2025-01-09  VIJAYAWADA             31          64     Rainy
4 2025-01-05    BANGLORE             32          57     Rainy
7 2025-01-08    BANGLORE             32          63    Cloudy
5 2025-01-06    BANGLORE             33          59     Rainy
6 2025-01-07    BANGLORE             34          61     Sunny